version: '3.8'

services:
  ollama-fake:
    build: .
    ports:
      - "11434:11434"
    environment:
      - PORT=11434
      - HOST=0.0.0.0
      - DEBUG=false
      - DEFAULT_MODEL=llama2
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 30s
      timeout: 10s
      retries: 3
